import { T } from "./theme.js";

export const s = {
  badge: (color, bg) => ({
    display: "inline-flex",
    padding: "1px 8px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 600,
    color: color || T.textSecondary,
    background: bg || T.surfaceAlt,
    fontFamily: T.font,
    whiteSpace: "nowrap",
    lineHeight: "20px",
  }),
  th: {
    padding: "10px 14px",
    textAlign: "left",
    fontSize: 12,
    fontWeight: 600,
    color: T.textTertiary,
    fontFamily: T.font,
    borderBottom: `1px solid ${T.border}`,
    whiteSpace: "nowrap",
    letterSpacing: 0.3,
    position: "sticky",
    top: 0,
    background: T.surface,
    zIndex: 1,
  },
  td: {
    padding: "10px 14px",
    fontSize: 13,
    color: T.text,
    fontFamily: T.font,
    borderBottom: `1px solid ${T.borderLight}`,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 200,
  },
  tdMono: {
    padding: "10px 14px",
    fontSize: 12,
    color: T.textSecondary,
    fontFamily: T.mono,
    borderBottom: `1px solid ${T.borderLight}`,
    whiteSpace: "nowrap",
  },
  link: { color: T.accent, cursor: "pointer", fontWeight: 500, textDecoration: "none" },
  input: {
    width: "100%",
    padding: "8px 12px",
    border: `1.5px solid ${T.border}`,
    borderRadius: T.radiusSm,
    fontSize: 14,
    color: T.text,
    fontFamily: T.font,
    outline: "none",
    background: T.surface,
    boxSizing: "border-box",
    WebkitAppearance: "none",
  },
  select: {
    padding: "6px 10px",
    border: `1.5px solid ${T.border}`,
    borderRadius: T.radiusSm,
    fontSize: 12,
    color: T.textSecondary,
    fontFamily: T.font,
    background: T.surface,
    cursor: "pointer",
    outline: "none",
  },
  btn: (primary) => ({
    padding: primary ? "8px 18px" : "6px 14px",
    borderRadius: T.radiusSm,
    border: primary ? "none" : `1.5px solid ${T.border}`,
    background: primary ? T.accent : T.surface,
    color: primary ? "#fff" : T.textSecondary,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: T.font,
    whiteSpace: "nowrap",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  }),
  btnDanger: {
    padding: "6px 14px",
    borderRadius: T.radiusSm,
    border: `1.5px solid #FCA5A5`,
    background: "#FFF",
    color: "#DC2626",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: T.font,
    whiteSpace: "nowrap",
  },
};
